//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaiHoaWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_OrderDetail
    {
        public int Id { get; set; }
        public Nullable<int> OderId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual tb_Oder tb_Oder { get; set; }
        public virtual tb_Product tb_Product { get; set; }
    }
}
